const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.GamePush_Channels,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Touch,
		C3.Plugins.Clipboard,
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.List,
		C3.Plugins.Button,
		C3.Behaviors.Pin,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Clipboard.Acts.CopyText,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.LoadState,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerID,
		C3.Plugins.List.Acts.SetVisible,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Cnds.CompareY,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Eponesh_GameScore.Cnds.PlayerCompare,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerAdd,
		C3.Plugins.List.Acts.AddItem,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerLogin,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.List.Acts.SetCSSStyle,
		C3.Plugins.Button.Acts.SetCSSStyle
	];
};
self.C3_JsPropNameTable = [
	{Якорь: 0},
	{Balance_txt: 0},
	{GamePushChannels: 0},
	{GamePush: 0},
	{Тач: 0},
	{ID_Bank_txt: 0},
	{БуферОбмена: 0},
	{Fon_Bar: 0},
	{Open_BarMenu: 0},
	{Твинанимация: 0},
	{Fon_BarMenu: 0},
	{Fon_BarMenu_Close: 0},
	{icons8подарок: 0},
	{TEXT: 0},
	{Список: 0},
	{Прикрепить: 0},
	{Вход: 0}
];

self.InstanceType = {
	Balance_txt: class extends self.ITextInstance {},
	GamePushChannels: class extends self.C3.Plugins.GamePush_Channels.Instance {},
	GamePush: class extends self.C3.Plugins.Eponesh_GameScore.Instance {},
	Тач: class extends self.IInstance {},
	ID_Bank_txt: class extends self.ITextInstance {},
	БуферОбмена: class extends self.IInstance {},
	Fon_Bar: class extends self.ITiledBackgroundInstance {},
	Open_BarMenu: class extends self.ISpriteInstance {},
	Fon_BarMenu: class extends self.ITiledBackgroundInstance {},
	Fon_BarMenu_Close: class extends self.ITiledBackgroundInstance {},
	icons8подарок: class extends self.ISpriteInstance {},
	TEXT: class extends self.ITextInstance {},
	Список: class extends self.IListInstance {},
	Вход: class extends self.IButtonInstance {}
}