const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.TextBox,
		C3.Plugins.Button,
		C3.Plugins.Browser,
		C3.Plugins.Sprite,
		C3.Plugins.GamePush_Channels,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.Clipboard,
		C3.Plugins.iframe,
		C3.Plugins.HTMLElement,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.Eponesh_GameScore.Cnds.PlayerCompare,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSetName,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerLogin,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerID,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Clipboard.Acts.CopyText,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Clipboard.Cnds.OnCopySuccess,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerAdd
	];
};
self.C3_JsPropNameTable = [
	{Тач: 0},
	{NickName: 0},
	{Create_Pay: 0},
	{Autorizen: 0},
	{Браузер: 0},
	{Picsart_250609_: 0},
	{GamePushChannels: 0},
	{GamePush: 0},
	{Gift_Objavlen: 0},
	{Спрайт: 0},
	{Balance_txt: 0},
	{ТайловыйФон: 0},
	{loader: 0},
	{ID_txt: 0},
	{БуферОбмена: 0},
	{processingin: 0},
	{TEXT: 0},
	{iframe: 0},
	{HTMLЭлемент: 0}
];

self.InstanceType = {
	Тач: class extends self.IInstance {},
	NickName: class extends self.ITextInputInstance {},
	Create_Pay: class extends self.IButtonInstance {},
	Autorizen: class extends self.IButtonInstance {},
	Браузер: class extends self.IInstance {},
	Picsart_250609_: class extends self.ISpriteInstance {},
	GamePushChannels: class extends self.C3.Plugins.GamePush_Channels.Instance {},
	GamePush: class extends self.C3.Plugins.Eponesh_GameScore.Instance {},
	Gift_Objavlen: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Balance_txt: class extends self.ITextInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	loader: class extends self.ISpriteInstance {},
	ID_txt: class extends self.ITextInstance {},
	БуферОбмена: class extends self.IInstance {},
	processingin: class extends self.ISpriteInstance {},
	TEXT: class extends self.ITextInstance {},
	iframe: class extends self.IIframeInstance {},
	HTMLЭлемент: class extends self.IHTMLElementInstance {}
}